
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('providers').del()
    .then(function () {
      // Inserts seed entries
      return knex('providers').insert([
        {id: 1, user_id: 1, first_name: 'Matthew', last_name: 'Adess', title: 'Gastrointestinal Oncologist', bio:'Dr. Matthew Adess is a Clinician Educator in medical oncology at NorthShore with an expertise in gastrointestinal cancer and benign hematology. He earned his medical degree from Loyola University of Chicago’s Stritch School of Medicine, where he also completed an internship, residency, and post-doctoral fellowship in hematology/oncology. Dr. Adess is an active member of the regional leadership board of the Lake County American Cancer Society.', gender:'M', age: 38, image:''},
        {id: 2, user_id: 2, first_name: 'Marshall', last_name: 'Baker', title: 'Surgical Oncologist', bio:'Dr. Marshall Baker is a board-certified surgeon with an expertise in general surgery, oncologic surgery, and pancreatic cancer. He is a Clinical Assistant Professor at the University of Chicago Pritzker School of Medicine. He earned his medical degree from Dartmouth Medical School and completed an internship at Georgetown University. Dr. Baker also completed a residency at Northwestern University, as well as a fellowship at both Northwestern University McGaw Medical Center and Indiana University School of Medicine.', gender:'M', age: 46, image:''},
        {id: 3, user_id: 3, first_name: 'Stacey', last_name: 'Becker', title: 'Physician Assistant', bio:'Stacey Becker is a nationally certified physician assistant specializing in thoracic oncology at NorthShore’s Kellogg Cancer Center. She completed her Bachelor of Arts degree in Behavioral Neuroscience from Lehigh University in Bethlehem, Pennsylvania and then earned her Master of Science at Arcadia University in Philadelphia, Pennsylvania. Ms. Becker is a past member of the Board of Directors for the Association of Physician Assistants in Oncology (APAO). She is certified by the National Commission for Certification of Physician Assistants.', gender:'F', age: 39, image:''},
        {id: 4, user_id: 4, first_name: 'Tiffany', last_name: 'Benfield', title: 'Nurse Practitioner', bio:'Tiffany Benfield is family nurse practitioner who specializes in head and neck cancer, sarcoma, melanoma and palliative care at NorthShore Kellogg Cancer Center. She completed her Bachelor of Science in Nursing at the University of North Carolina at Charlotte and then earned her Master of Science degree at DePaul University in Chicago, Illinois. She holds two national board certifications with the American Nurses Credentialing Center (ANCC) as a family nurse practitioner as well as a palliative care nurse practitioner', gender:'M', age: 42, image:''},
        {id: 5, user_id: 5, first_name: 'Mihir', last_name: 'Bhayani', title: 'physiotherapist', bio:'Dr. Mihir Bhayani is a board certified otolaryngologist with specialty expertise in head and neck cancer. Dr. Bhayani earned his medical degree from the University of Utah School of Medicine. He completed his residency in otolaryngology-head and neck surgery at University of Chicago Hospitals and completed fellowship training in head and neck surgery at University of Texas-M.D. Anderson Cancer Center. In addition to English, Dr. Bhayani speaks Gujurati.', gender:'M', age: 44, image:''},
        {id: 6, user_id: 6, first_name: 'William', last_name: 'Bloomer', title: 'Radiation Oncologist', bio:'Dr. Bloomer is Clinical Professor of Cellular and Radiation Oncology at the University of Chicago Pritzker School of Medicine. He is board certified in both therapeutic radiology and nuclear medicine. He has expertise in breast, prostate, lung and gastrointestinal cancer. He trained at Harvard Medical School and was on the faculty there for 12 years. Before coming to NorthShore, he had been the Benedum Professor and Chairman of Radiation Oncology at the University of Pittsburgh.', gender:'M', age: 60, image:''},
        {id: 7, user_id: 7, first_name: 'Tammy', last_name: 'Brown', title: 'Nurse Practitioner', bio:'Tammy Brown is an adult nurse practitioner who specializes in gastrointestinal oncology at NorthShore Kellogg Cancer Center. She completed her Bachelor of Science in Nursing at Lamar University in Beaumont, Texas and then earned her Master of Science degree at North Park University in Chicago, Illinois. She holds a national certification with the American Academy of Nurse Practitioners.', gender:'F', age: 41, image:''},
        {id: 8, user_id: 8, first_name: 'Nicholas', last_name: 'Campbell', title: 'Thoracic Oncologist', bio:'Dr. Nicholas Campbell is a medical oncologist with an expertise in thoracic, head and neck malignancies. He earned his medical degree at the Medical College of Georgia and completed both his residency in Internal Medicine and then fellowship in Medical Hematology/Oncology at the University of Chicago where he served as Chief Fellow. Dr. Campbell’s clinical research interests include novel therapeutics, trial development, and bio-repository database management.', gender:'M', age: 39, image:''},
        {id: 9, user_id: 9, first_name: 'Alla', last_name: 'Gimelfarb', title: 'Hematology Oncologist', bio:'Dr. Alla Gimelfarb is a hematology oncologist with expertise in benign and malignant hematology as well as thoracic oncology. She is a Clinician Educator at University of Chicago Pritzker School of Medicine. She earned her medical degree at the University of Illinois at Chicago and completed her internship, residency, and post-doctoral fellowship in hematology/oncology at Rush University Medical Center. Dr. Gimelfarb speaks both English and Russian.', gender:'F', age: 31, image:''},
        {id: 10, user_id: 10, first_name: 'Britt', last_name: 'Hanson', title: 'Hematology Oncologist', bio:'Dr. Britt Hanson is a board-certified hematologist with expertise in lung cancer and melanoma. She earned her medical degree from Des Moines University College of Osteopathic Medicine and completed post-doctoral fellowship training in hematology/oncology at Loyola University Medical Center/Hines Veterans Administration. Dr. Hanson is a Clinician Educator at the University of Chicago Pritzker School of Medicine.', gender:'F', age: 45, image:''},
      ]);
    });
};
